### PR TITLE
Fix public collection

### LINKED ISSUE #18: View site in public collection
The problem when clicking view the site in public collection.

### PR DESCRIPTION
**Pull request by Thyda-Eng**
Fix #18

### CODE REVIEW

File: app/controllers/sites_controller.rb [hunk 1]
```diff
@@ -33,10 +33,9 @@ class SitesController < ApplicationController
 
   def index
     search = new_search
-
     search.name_start_with params[:name] if params[:name].present?
     search.alerted_search params[:_alert] if params[:_alert] == "true"
-    search.my_site_search current_user.id unless current_user.can_view_other? params[:collection_id]
+    search.my_site_search current_user.id if !current_user.is_guest && !current_user.can_view_other?(params[:collection_id])
```
Comment (kakada) [inline app/controllers/sites_controller.rb]: Seem searching my site is contrast with condition, I can search only when I can't view the other otherwise I can't

File: app/controllers/sites_controller.rb [hunk 2]
```diff
@@ -163,7 +136,7 @@ def search_by_collection collection_id, params
     search.after params[:updated_since] if params[:updated_since]
     search.full_text_search params[:search] if params[:search].present?
     search.alerted_search params[:_alert] if params[:_alert].present?
-    search.my_site_search current_user.id unless current_user.can_view_other? collection_id
+    search.my_site_search current_user.id if current_user && !current_user.can_view_other?(collection_id)
```
Comment (kakada) [inline app/controllers/sites_controller.rb]: Seem searching my site is contrast with condition, I can search only when I can't view the other otherwise I can't

File: app/controllers/sites_controller.rb [hunk 3]
```diff
@@ -226,7 +175,7 @@ def search_alert_site_by_collection collection_id, params
     search.exclude_id params[:exclude_id].to_i if params[:exclude_id].present?
     search.full_text_search params[:search] if params[:search].present?
     search.alerted_search params[:_alert] if params[:_alert].present?
-    search.my_site_search current_user.id unless current_user.can_view_other? collection_id
+    search.my_site_search current_user.id if current_user && !current_user.can_view_other?(collection_id)
```
Comment (kakada) [inline app/controllers/sites_controller.rb]: Seem searching my site is contrast with condition, I can search only when I can't view the other otherwise I can't
